defaultNamespace: default

helm:
  values:
    clusterName: "Generic Fleet Cluster"

targetCustomizations:
  - name: development-clusters
    clusterSelector:
      matchLabels:
        environment: dev
    helm:
      values:
        clusterName: "US-West-Dev-Cluster"

  - name: production-clusters
    clusterSelector:
      matchLabels:
        environment: prod
    helm:
      values:
        clusterName: "EU-Central-Production-Cluster"
